trigger: 
- master

pool: 
  vmImage: 'ubuntu-16.04'


stages:
- stage: Build_Stage
  displayName: 
  jobs:
  - job: BuildNuget
    displayName: Build Nuget Packages
    variables: 
      BuildConfiguration: release
    steps: 

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      inputs:
        azureSubscription: 'Pay-As-You-Go(1)(66bc95b7-5c49-4ea6-abcc-38ae21688cf2)'
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        
    - task: DotNetCoreCLI@2
      inputs:
        azureSubscription: 'Pay-As-You-Go(1)(66bc95b7-5c49-4ea6-abcc-38ae21688cf2)'
        command: 'pack'
        packagesToPack: '**/*.csproj'
        versioningScheme: 'off'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '5151abf1-2d0f-46f4-86d2-bc6b9b93b545/c0119e2b-4376-4724-a85a-cf6250207c83'





